"""add product_line to bullet

Revision ID: 289db731eb1b
Revises: e1f2a3b4c5d6
Create Date: 2026-03-06 23:12:11.589956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289db731eb1b'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bullet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_line', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_bullet_product_line'), ['product_line'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bullet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bullet_product_line'))
        batch_op.drop_column('product_line')

    # ### end Alembic commands ###
