"""add_parent_company_to_manufacturer

Revision ID: 34d85577254b
Revises: bdbb8bfc39ef
Create Date: 2026-02-28 08:26:50.209987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d85577254b'
down_revision: Union[str, Sequence[str], None] = 'bdbb8bfc39ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_company', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.drop_column('parent_company')

    # ### end Alembic commands ###
