"""Add platform and caliber_platform tables

Revision ID: 71b236f2e2d0
Revises: fd28d4167e8a
Create Date: 2026-02-28 00:00:45.774021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b236f2e2d0'
down_revision: Union[str, Sequence[str], None] = 'fd28d4167e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_name'), ['name'], unique=True)

    op.create_table('caliber_platform',
    sa.Column('caliber_id', sa.String(length=36), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caliber_id'], ['caliber.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('caliber_id', 'platform_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caliber_platform')
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_name'))

    op.drop_table('platform')
    # ### end Alembic commands ###
