"""add_short_name_to_manufacturer

Revision ID: 7ca937a28e4d
Revises: 289db731eb1b
Create Date: 2026-03-11 08:51:46.338306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca937a28e4d'
down_revision: Union[str, Sequence[str], None] = '289db731eb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manufacturer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("short_name", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###

    # Populate short_name for all existing manufacturers.
    # Rules: known abbreviations for well-known brands; single-word names stay as-is;
    # multi-word names use first word unless a specific abbreviation is defined.
    short_names = {
        "Accuracy International": "AI",
        "Aero Precision": "Aero",
        "Alpha Munitions": "Alpha",
        "Applied Ballistics": "AB",
        "Area 419": "A419",
        "Arken Optics": "Arken",
        "Athlon Optics": "Athlon",
        "Barnes Bullets": "Barnes",
        "Bartlein Barrels": "Bartlein",
        "Bergara": "Bergara",
        "Berger Bullets": "Berger",
        "Black Hills Ammunition": "BH",
        "Bravo Company": "BCM",
        "Browning": "Brng",
        "Bushnell": "Bush",
        "CZ (Česká zbrojovka)": "CZ",
        "Cadex Defence": "Cadex",
        "Christensen Arms": "CA",
        "Criterion Barrels": "Criterion",
        "Curtis Custom": "Curtis",
        "Cutting Edge Bullets": "CE",
        "Daniel Defense": "DD",
        "Defiance Machine": "Defiance",
        "Desert Tech": "DT",
        "Element Optics": "Element",
        "Federal": "Fed",
        "Foundation Stocks": "Foundation",
        "GA Precision": "GAP",
        "Garmin": "Garmin",
        "Geissele Automatics": "Geissele",
        "Grayboe": "Grayboe",
        "Hammer Bullets": "Hammer",
        "Hornady": "Hndy",
        "Howa": "Howa",
        "IMI Systems": "IMI",
        "Impact Precision": "Impact",
        "JP Enterprises": "JP",
        "KRG (Kinetic Research Group)": "KRG",
        "Kahles": "Kahles",
        "Kestrel Ballistics": "Kestrel",
        "Knight's Armament": "KAC",
        "LWRC International": "LWRC",
        "LaRue Tactical": "LaRue",
        "Lapua": "Lapua",
        "Lehigh Defense": "Lehigh",
        "Leupold": "Leupold",
        "Lewis Machine & Tool": "LMT",
        "MDT (Modular Driven Technologies)": "MDT",
        "Manners Composite Stocks": "Manners",
        "March Optics": "March",
        "Masterpiece Arms": "MPA",
        "Maven": "Maven",
        "McMillan": "McMillan",
        "Mossberg": "Moss",
        "Nightforce Optics": "NF",
        "Norma": "Norma",
        "Nosler": "Nosler",
        "Palmetto State Armory": "PSA",
        "Peterson Cartridge": "Peterson",
        "Proof Research": "Proof",
        "Prvi Partizan": "PPU",
        "Remington": "Rem",
        "Revic": "Revic",
        "Ruger": "Ruger",
        "Sako": "Sako",
        "Savage Arms": "Savage",
        "Schmidt & Bender": "S&B",
        "Seekins Precision": "Seekins",
        "Sellier & Bellot": "S&B",
        "Sierra Bullets": "Sierra",
        "Sig Sauer": "Sig",
        "Speer": "Speer",
        "Starline Brass": "Starline",
        "Steiner": "Steiner",
        "Swarovski Optik": "Swaro",
        "Tangent Theta": "TT",
        "Tikka": "Tikka",
        "Timney Triggers": "Timney",
        "TriggerTech": "TriggerTech",
        "US Optics": "USO",
        "Vortex Optics": "Vortex",
        "Weatherby": "Wby",
        "Winchester": "Win",
        "XLR Industries": "XLR",
        "Zermatt Arms": "Zermatt",
        "Zero Compromise Optics": "ZCO",
    }

    manufacturer = sa.table("manufacturer", sa.column("name", sa.String), sa.column("short_name", sa.String))
    for name, short in short_names.items():
        op.execute(manufacturer.update().where(manufacturer.c.name == name).values(short_name=short))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
