"""add display_name to bullet, cartridge

Revision ID: 94fc26fd30ce
Revises: 7ca937a28e4d
Create Date: 2026-03-18 21:23:15.054930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fc26fd30ce'
down_revision: Union[str, Sequence[str], None] = '7ca937a28e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bullet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('cartridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridge', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    with op.batch_alter_table('bullet', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
