"""initial schema

Revision ID: 9fb22e6478ee
Revises:
Create Date: 2026-02-20 10:39:52.227728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fb22e6478ee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caliber",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("bullet_diameter_inches", sa.Float(), nullable=False),
        sa.Column("case_length_inches", sa.Float(), nullable=True),
        sa.Column("saami_designation", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("popularity_rank", sa.Integer(), nullable=True),
        sa.Column("coal_inches", sa.Float(), nullable=True),
        sa.Column("max_pressure_psi", sa.Integer(), nullable=True),
        sa.Column("rim_type", sa.String(length=50), nullable=True),
        sa.Column("action_length", sa.String(length=50), nullable=True),
        sa.Column("parent_caliber_id", sa.String(length=36), nullable=True),
        sa.Column("year_introduced", sa.Integer(), nullable=True),
        sa.Column("is_common_lr", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_caliber_id"],
            ["caliber.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("caliber", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_caliber_name"), ["name"], unique=True)

    op.create_table(
        "chamber",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chamber", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chamber_name"), ["name"], unique=True)

    op.create_table(
        "entity_alias",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("alias_type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_id", "alias", name="uq_entity_alias"),
    )
    with op.batch_alter_table("entity_alias", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_alias_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_entity_alias_entity_type"), ["entity_type"], unique=False)

    op.create_table(
        "manufacturer",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("type_tags", sa.JSON(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("manufacturer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manufacturer_name"), ["name"], unique=True)

    op.create_table(
        "bullet",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("caliber_id", sa.String(length=36), nullable=False),
        sa.Column("weight_grains", sa.Float(), nullable=False),
        sa.Column("bc_g1_published", sa.Float(), nullable=True),
        sa.Column("bc_g1_estimated", sa.Float(), nullable=True),
        sa.Column("bc_g7_published", sa.Float(), nullable=True),
        sa.Column("bc_g7_estimated", sa.Float(), nullable=True),
        sa.Column("bc_source_notes", sa.Text(), nullable=True),
        sa.Column("length_inches", sa.Float(), nullable=True),
        sa.Column("sectional_density", sa.Float(), nullable=True),
        sa.Column("type_tags", sa.JSON(), nullable=True),
        sa.Column("used_for", sa.JSON(), nullable=True),
        sa.Column("base_type", sa.String(length=50), nullable=True),
        sa.Column("tip_type", sa.String(length=50), nullable=True),
        sa.Column("construction", sa.String(length=50), nullable=True),
        sa.Column("is_lead_free", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("popularity_rank", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["caliber_id"],
            ["caliber.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bullet_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bullet_sku"), ["sku"], unique=False)

    op.create_table(
        "chamber_accepts_caliber",
        sa.Column("chamber_id", sa.String(length=36), nullable=False),
        sa.Column("caliber_id", sa.String(length=36), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["caliber_id"],
            ["caliber.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chamber_id"],
            ["chamber.id"],
        ),
        sa.PrimaryKeyConstraint("chamber_id", "caliber_id"),
    )
    op.create_table(
        "rifle_model",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("manufacturer_url", sa.String(length=500), nullable=True),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("chamber_id", sa.String(length=36), nullable=False),
        sa.Column("barrel_length_inches", sa.Float(), nullable=True),
        sa.Column("twist_rate", sa.String(length=20), nullable=True),
        sa.Column("weight_lbs", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("barrel_material", sa.String(length=100), nullable=True),
        sa.Column("barrel_finish", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chamber_id"],
            ["chamber.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rifle_model_model"), ["model"], unique=False)

    op.create_table(
        "bullet_bc_source",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bullet_id", sa.String(length=36), nullable=False),
        sa.Column("bc_type", sa.String(length=10), nullable=False),
        sa.Column("bc_value", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_quality", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bullet_id"],
            ["bullet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cartridge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("product_line", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("caliber_id", sa.String(length=36), nullable=False),
        sa.Column("bullet_id", sa.String(length=36), nullable=False),
        sa.Column("bullet_weight_grains", sa.Float(), nullable=False),
        sa.Column("muzzle_velocity_fps", sa.Integer(), nullable=False),
        sa.Column("test_barrel_length_inches", sa.Float(), nullable=True),
        sa.Column("round_count", sa.Integer(), nullable=True),
        sa.Column("bullet_match_confidence", sa.Float(), nullable=True),
        sa.Column("bullet_match_method", sa.String(length=50), nullable=True),
        sa.Column("popularity_rank", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bullet_id"],
            ["bullet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["caliber_id"],
            ["caliber.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cartridge", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cartridge_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_cartridge_sku"), ["sku"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cartridge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cartridge_sku"))
        batch_op.drop_index(batch_op.f("ix_cartridge_name"))

    op.drop_table("cartridge")
    op.drop_table("bullet_bc_source")
    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rifle_model_model"))

    op.drop_table("rifle_model")
    op.drop_table("chamber_accepts_caliber")
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bullet_sku"))
        batch_op.drop_index(batch_op.f("ix_bullet_name"))

    op.drop_table("bullet")
    with op.batch_alter_table("manufacturer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manufacturer_name"))

    op.drop_table("manufacturer")
    with op.batch_alter_table("entity_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_alias_entity_type"))
        batch_op.drop_index(batch_op.f("ix_entity_alias_entity_id"))

    op.drop_table("entity_alias")
    with op.batch_alter_table("chamber", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chamber_name"))

    op.drop_table("chamber")
    with op.batch_alter_table("caliber", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_caliber_name"))

    op.drop_table("caliber")
    # ### end Alembic commands ###
