"""add twist_rate_inches, saami_test_barrel_length, source_methodology

- rifle_model.twist_rate_inches: numeric twist rate for Miller stability calc
  (backfilled from existing twist_rate string column, e.g. "1:8" -> 8.0)
- caliber.saami_test_barrel_length_inches: SAAMI standard test barrel length
  for MV fallback when manufacturer doesn't publish test barrel length
  (seeded for common calibers)
- bullet_bc_source.source_methodology: how the BC was measured
  (e.g. "doppler", "theoretical", "ballistic_pendulum")

Revision ID: e015cb9c96e8
Revises: 34d85577254b
Create Date: 2026-02-28 09:01:33.215684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e015cb9c96e8"
down_revision: Union[str, Sequence[str], None] = "34d85577254b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bullet_bc_source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_methodology", sa.String(length=50), nullable=True))

    with op.batch_alter_table("caliber", schema=None) as batch_op:
        batch_op.add_column(sa.Column("saami_test_barrel_length_inches", sa.Float(), nullable=True))

    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("twist_rate_inches", sa.Float(), nullable=True))

    # ### end Alembic commands ###

    # Backfill twist_rate_inches from twist_rate string (e.g. "1:8" -> 8.0)
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, twist_rate FROM rifle_model WHERE twist_rate IS NOT NULL")).fetchall()
    for row_id, twist_str in rows:
        if ":" in twist_str:
            try:
                numeric = float(twist_str.split(":")[1])
                conn.execute(
                    sa.text("UPDATE rifle_model SET twist_rate_inches = :val WHERE id = :id"),
                    {"val": numeric, "id": row_id},
                )
            except (ValueError, IndexError):
                pass  # Skip malformed values

    # Seed SAAMI standard test barrel lengths for common calibers
    saami_barrel_lengths = {
        ".223 Remington": 24.0,
        "5.56x45mm NATO": 20.0,
        ".243 Winchester": 24.0,
        "6mm Creedmoor": 24.0,
        "6mm ARC": 24.0,
        "6.5 Creedmoor": 24.0,
        "6.5 PRC": 24.0,
        ".260 Remington": 24.0,
        ".270 Winchester": 24.0,
        "7mm-08 Remington": 24.0,
        "7mm Remington Magnum": 24.0,
        "7mm PRC": 24.0,
        ".308 Winchester": 24.0,
        "7.62x51mm NATO": 24.0,
        ".30-06 Springfield": 24.0,
        ".300 Winchester Magnum": 24.0,
        ".300 Winchester Short Magnum": 24.0,
        ".300 PRC": 24.0,
        ".300 AAC Blackout": 16.0,
        ".338 Lapua Magnum": 27.0,
    }
    for caliber_name, barrel_len in saami_barrel_lengths.items():
        conn.execute(
            sa.text("UPDATE caliber SET saami_test_barrel_length_inches = :val WHERE name = :name"),
            {"val": barrel_len, "name": caliber_name},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.drop_column("twist_rate_inches")

    with op.batch_alter_table("caliber", schema=None) as batch_op:
        batch_op.drop_column("saami_test_barrel_length_inches")

    with op.batch_alter_table("bullet_bc_source", schema=None) as batch_op:
        batch_op.drop_column("source_methodology")

    # ### end Alembic commands ###
