"""Add Reticle, Optic tables and RifleModel model_family

Revision ID: fd28d4167e8a
Revises: 9fb22e6478ee
Create Date: 2026-02-20 13:47:14.054873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fd28d4167e8a"
down_revision: Union[str, Sequence[str], None] = "9fb22e6478ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reticle",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reticle", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reticle_name"), ["name"], unique=True)

    op.create_table(
        "optic",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("alt_names", sa.JSON(), nullable=True),
        sa.Column("model_family", sa.String(length=255), nullable=True),
        sa.Column("product_line", sa.String(length=255), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("reticle_id", sa.String(length=36), nullable=False),
        sa.Column("click_unit", sa.String(length=10), nullable=False),
        sa.Column("click_value", sa.Float(), nullable=False),
        sa.Column("magnification_min", sa.Float(), nullable=False),
        sa.Column("magnification_max", sa.Float(), nullable=False),
        sa.Column("objective_diameter_mm", sa.Float(), nullable=False),
        sa.Column("tube_diameter_mm", sa.Float(), nullable=False),
        sa.Column("focal_plane", sa.String(length=10), nullable=False),
        sa.Column("elevation_travel_mils", sa.Float(), nullable=True),
        sa.Column("windage_travel_mils", sa.Float(), nullable=True),
        sa.Column("weight_oz", sa.Float(), nullable=True),
        sa.Column("length_inches", sa.Float(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reticle_id"],
            ["reticle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("optic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_optic_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_optic_sku"), ["sku"], unique=False)

    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_family", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rifle_model", schema=None) as batch_op:
        batch_op.drop_column("model_family")

    with op.batch_alter_table("optic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_optic_sku"))
        batch_op.drop_index(batch_op.f("ix_optic_name"))

    op.drop_table("optic")
    with op.batch_alter_table("reticle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reticle_name"))

    op.drop_table("reticle")
    # ### end Alembic commands ###
