"""Generate a markdown summary of the current drift.db contents.

Usage:
    python scripts/describe_db.py               # write to docs/db_summary.md
    python scripts/describe_db.py --stdout       # print to stdout instead
    python scripts/describe_db.py -o path.md     # write to custom path

Designed for iOS engineers who rely on the bundled drift.db. Re-run any time
the database changes to get an updated snapshot.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = _ROOT / "data" / "drift.db"
DEFAULT_OUT = _ROOT / "docs" / "db_summary.md"

# Tables in logical display order.
TABLE_ORDER = [
    "manufacturer",
    "caliber",
    "chamber",
    "platform",
    "bullet",
    "bullet_bc_source",
    "cartridge",
    "rifle_model",
    "optic",
    "reticle",
    "caliber_platform",
    "chamber_accepts_caliber",
    "entity_alias",
]


def _q(conn: sqlite3.Connection, sql: str) -> list[sqlite3.Row]:
    return conn.execute(sql).fetchall()


def _q1(conn: sqlite3.Connection, sql: str):
    return conn.execute(sql).fetchone()


def build_summary(conn: sqlite3.Connection) -> str:
    lines: list[str] = []
    w = lines.append

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    db_size = os.path.getsize(DB_PATH)
    db_kb = db_size / 1024

    w("# Drift Database Summary")
    w("")
    w(f"> Auto-generated by `scripts/describe_db.py` on {now}")
    w(f"> Source: `data/drift.db` ({db_kb:.0f} KB)")
    w("")

    # ── Row counts ──────────────────────────────────────────────
    w("## Row Counts")
    w("")
    w("| Table | Rows | Description |")
    w("|-------|-----:|-------------|")

    table_descs = {
        "manufacturer": "Companies (bullet, ammo, rifle, optic makers)",
        "caliber": "Cartridge designations with popularity rankings",
        "chamber": "Firearm chamber specifications",
        "platform": "Action types (Bolt Action, AR-15, AR-10)",
        "bullet": "Individual projectile specs (weight, BC, geometry)",
        "bullet_bc_source": "Multi-source BC audit trail",
        "cartridge": "Factory-loaded ammunition (bullet + caliber + MV)",
        "rifle_model": "Factory rifle configurations",
        "optic": "Riflescope specifications",
        "reticle": "Reticle patterns and units",
        "caliber_platform": "Junction: calibers available per platform",
        "chamber_accepts_caliber": "Junction: calibers a chamber can fire",
        "entity_alias": "Alternative names for search (pipeline metadata)",
    }

    total = 0
    for table in TABLE_ORDER:
        count = _q1(conn, f"SELECT COUNT(*) FROM {table}")[0]
        total += count
        desc = table_descs.get(table, "")
        w(f"| `{table}` | {count} | {desc} |")
    w(f"| **Total** | **{total}** | |")
    w("")

    # ── Manufacturers ───────────────────────────────────────────
    w("## Manufacturers")
    w("")
    rows = _q(
        conn,
        """
        SELECT
            SUM(CASE WHEN type_tags LIKE '%bullet_maker%' THEN 1 ELSE 0 END),
            SUM(CASE WHEN type_tags LIKE '%ammo_maker%' THEN 1 ELSE 0 END),
            SUM(CASE WHEN type_tags LIKE '%rifle_maker%' THEN 1 ELSE 0 END),
            SUM(CASE WHEN type_tags LIKE '%optic_maker%' THEN 1 ELSE 0 END),
            COUNT(*)
        FROM manufacturer
        """,
    )
    bullet_m, ammo_m, rifle_m, optic_m, total_m = rows[0]
    w(f"**{total_m} manufacturers** — {bullet_m} bullet makers, {ammo_m} ammo makers, {rifle_m} rifle makers, {optic_m} optic makers.")
    w("(Manufacturers can have multiple type tags.)")
    w("")

    # ── Calibers ────────────────────────────────────────────────
    w("## Calibers")
    w("")
    cal_total = _q1(conn, "SELECT COUNT(*) FROM caliber")[0]
    lr_count = _q1(conn, "SELECT COUNT(*) FROM caliber WHERE is_common_lr = 1")[0]
    ranked_overall = _q1(conn, "SELECT COUNT(*) FROM caliber WHERE overall_popularity_rank IS NOT NULL")[0]
    ranked_lr = _q1(conn, "SELECT COUNT(*) FROM caliber WHERE lr_popularity_rank IS NOT NULL")[0]
    w(f"**{cal_total} calibers** — {lr_count} flagged as common long-range, {ranked_overall} with overall popularity ranking, {ranked_lr} with LR ranking.")
    w("")

    w("### Top 20 Overall Calibers")
    w("")
    w("| Rank | Caliber | LR Rank | Common LR |")
    w("|-----:|---------|--------:|:---------:|")
    for row in _q(
        conn,
        """SELECT name, overall_popularity_rank, lr_popularity_rank, is_common_lr
           FROM caliber WHERE overall_popularity_rank IS NOT NULL
           ORDER BY overall_popularity_rank LIMIT 20""",
    ):
        name, overall, lr, is_lr = row
        lr_str = str(lr) if lr else "—"
        is_lr_str = "yes" if is_lr else ""
        w(f"| {overall} | {name} | {lr_str} | {is_lr_str} |")
    w("")

    w("### Top 15 Long-Range Calibers")
    w("")
    w("| LR Rank | Caliber | Overall Rank |")
    w("|--------:|---------|-------------:|")
    for row in _q(
        conn,
        """SELECT name, lr_popularity_rank, overall_popularity_rank
           FROM caliber WHERE lr_popularity_rank IS NOT NULL
           ORDER BY lr_popularity_rank LIMIT 15""",
    ):
        name, lr, overall = row
        overall_str = str(overall) if overall else "—"
        w(f"| {lr} | {name} | {overall_str} |")
    w("")

    # ── Platforms ───────────────────────────────────────────────
    w("## Platforms")
    w("")
    w("| Platform | Calibers Available |")
    w("|----------|-------------------:|")
    for row in _q(
        conn,
        """SELECT p.name, COUNT(cp.caliber_id)
           FROM platform p
           LEFT JOIN caliber_platform cp ON cp.platform_id = p.id
           GROUP BY p.id ORDER BY COUNT(cp.caliber_id) DESC""",
    ):
        w(f"| {row[0]} | {row[1]} |")
    w("")

    # ── Bullets ─────────────────────────────────────────────────
    w("## Bullets")
    w("")
    bullet_count = _q1(conn, "SELECT COUNT(*) FROM bullet")[0]
    w(f"**{bullet_count} bullets** across the following calibers:")
    w("")
    w("| Diameter (in) | Count | Weight Range (gr) | Manufacturers |")
    w("|---------------|------:|------------------:|---------------|")
    for row in _q(
        conn,
        """SELECT PRINTF('%.3f', b.bullet_diameter_inches),
                  COUNT(b.id),
                  MIN(b.weight_grains) || '–' || MAX(b.weight_grains),
                  GROUP_CONCAT(DISTINCT m.name)
           FROM bullet b
           LEFT JOIN manufacturer m ON b.manufacturer_id = m.id
           GROUP BY PRINTF('%.3f', b.bullet_diameter_inches)
           ORDER BY b.bullet_diameter_inches""",
    ):
        w(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} |")
    w("")

    # Bullet detail
    w("### Full Bullet List")
    w("")
    w("| Bullet | Diameter (in) | Weight (gr) | G1 BC | G7 BC | Manufacturer |")
    w("|--------|---------------|------------:|------:|------:|--------------|")
    for row in _q(
        conn,
        """SELECT b.name, PRINTF('%.3f', b.bullet_diameter_inches), b.weight_grains,
                  b.bc_g1_published, b.bc_g7_published, m.name
           FROM bullet b
           LEFT JOIN manufacturer m ON b.manufacturer_id = m.id
           ORDER BY b.bullet_diameter_inches, b.weight_grains""",
    ):
        name, dia, wt, g1, g7, mfr = row
        g1_str = f"{g1:.3f}" if g1 else "—"
        g7_str = f"{g7:.3f}" if g7 else "—"
        wt_str = f"{wt:.0f}" if wt else "—"
        w(f"| {name} | {dia} | {wt_str} | {g1_str} | {g7_str} | {mfr or '—'} |")
    w("")

    # ── Cartridges ──────────────────────────────────────────────
    w("## Cartridges (Factory Loads)")
    w("")
    cart_count = _q1(conn, "SELECT COUNT(*) FROM cartridge")[0]
    w(f"**{cart_count} factory loads** across the following calibers:")
    w("")
    w("| Caliber | Count | Manufacturers |")
    w("|---------|------:|---------------|")
    for row in _q(
        conn,
        """SELECT c.name, COUNT(ct.id), GROUP_CONCAT(DISTINCT m.name)
           FROM cartridge ct
           JOIN caliber c ON ct.caliber_id = c.id
           LEFT JOIN manufacturer m ON ct.manufacturer_id = m.id
           GROUP BY c.id ORDER BY c.lr_popularity_rank""",
    ):
        w(f"| {row[0]} | {row[1]} | {row[2]} |")
    w("")

    w("### Full Cartridge List")
    w("")
    w("| Cartridge | Caliber | Weight (gr) | MV (fps) | Manufacturer |")
    w("|-----------|---------|------------:|---------:|--------------|")
    for row in _q(
        conn,
        """SELECT ct.name, c.name, ct.bullet_weight_grains,
                  ct.muzzle_velocity_fps, m.name
           FROM cartridge ct
           JOIN caliber c ON ct.caliber_id = c.id
           LEFT JOIN manufacturer m ON ct.manufacturer_id = m.id
           ORDER BY c.lr_popularity_rank, ct.bullet_weight_grains""",
    ):
        name, cal, wt, mv, mfr = row
        wt_str = f"{wt:.0f}" if wt else "—"
        mv_str = str(mv) if mv else "—"
        w(f"| {name} | {cal} | {wt_str} | {mv_str} | {mfr or '—'} |")
    w("")

    # ── Rifle Models ────────────────────────────────────────────
    w("## Rifle Models")
    w("")
    rifle_count = _q1(conn, "SELECT COUNT(*) FROM rifle_model")[0]
    w(f"**{rifle_count} rifle models:**")
    w("")
    w("| Model | Manufacturer | Chamber | Barrel (in) | Twist |")
    w("|-------|--------------|---------|------------:|-------|")
    for row in _q(
        conn,
        """SELECT r.model, m.name, ch.name, r.barrel_length_inches, r.twist_rate
           FROM rifle_model r
           LEFT JOIN manufacturer m ON r.manufacturer_id = m.id
           LEFT JOIN chamber ch ON r.chamber_id = ch.id
           ORDER BY ch.name, r.barrel_length_inches""",
    ):
        model, mfr, chamber, bbl, twist = row
        bbl_str = f"{bbl:.0f}" if bbl else "—"
        w(f"| {model} | {mfr or '—'} | {chamber or '—'} | {bbl_str} | {twist or '—'} |")
    w("")

    # ── Optics ──────────────────────────────────────────────────
    w("## Optics")
    w("")
    optic_count = _q1(conn, "SELECT COUNT(*) FROM optic")[0]
    reticle_count = _q1(conn, "SELECT COUNT(*) FROM reticle")[0]
    w(f"**{optic_count} optics**, **{reticle_count} reticles**")
    w("")
    w("| Optic | Manufacturer | Reticle | Unit | Focal Plane | Magnification |")
    w("|-------|--------------|---------|------|:-----------:|--------------:|")
    for row in _q(
        conn,
        """SELECT o.name, m.name, r.name, o.click_unit, o.focal_plane,
                  o.magnification_min || '-' || o.magnification_max || 'x'
           FROM optic o
           LEFT JOIN manufacturer m ON o.manufacturer_id = m.id
           LEFT JOIN reticle r ON o.reticle_id = r.id
           ORDER BY m.name, o.name""",
    ):
        name, mfr, ret, unit, fp, mag = row
        fp_str = (fp or "—").upper()
        w(f"| {name} | {mfr or '—'} | {ret or '—'} | {unit or '—'} | {fp_str} | {mag} |")
    w("")

    # ── Coverage gaps ───────────────────────────────────────────
    w("## Coverage Gaps")
    w("")
    w("Calibers in the top 15 LR rankings that have **no bullets or cartridges** yet:")
    w("")
    gaps = _q(
        conn,
        """SELECT c.name, c.lr_popularity_rank
           FROM caliber c
           WHERE c.lr_popularity_rank IS NOT NULL AND c.lr_popularity_rank <= 15
           AND NOT EXISTS (
               SELECT 1 FROM bullet b
               WHERE ABS(b.bullet_diameter_inches - c.bullet_diameter_inches) < 0.001
           )
           AND c.id NOT IN (SELECT DISTINCT caliber_id FROM cartridge)
           ORDER BY c.lr_popularity_rank""",
    )
    if gaps:
        for row in gaps:
            w(f"- **{row[0]}** (LR rank #{row[1]})")
    else:
        w("None — all top 15 LR calibers have at least one bullet or cartridge.")
    w("")

    # ── Schema reference ────────────────────────────────────────
    w("## Schema Reference")
    w("")
    w("Key columns by table (not exhaustive — see `src/drift/models/` for full definitions).")
    w("")
    schema_notes = {
        "manufacturer": "name, alt_names (JSON), type_tags (JSON), website_url, country, parent_company",
        "caliber": "name, alt_names (JSON), bullet_diameter_inches, overall_popularity_rank, lr_popularity_rank, is_common_lr, parent_caliber_id (FK self)",
        "chamber": "name, alt_names (JSON). Junction: `chamber_accepts_caliber` (chamber_id, caliber_id, is_primary)",
        "platform": "name, short_name. Junction: `caliber_platform` (caliber_id, platform_id, popularity_rank)",
        "bullet": "name, manufacturer_id, bullet_diameter_inches, weight_grains, bc_g1_published, bc_g7_published, type_tags (JSON), base_type, tip_type",
        "cartridge": "name, manufacturer_id, caliber_id, bullet_id, bullet_weight_grains, muzzle_velocity_fps, test_barrel_length_inches",
        "rifle_model": "model, manufacturer_id, chamber_id, barrel_length_inches, twist_rate, twist_rate_inches",
        "optic": "name, manufacturer_id, reticle_id, click_unit (mil/moa), click_value, magnification_min/max, focal_plane (ffp/sfp)",
        "reticle": "name, alt_names (JSON), unit (mil/moa), manufacturer_id",
    }
    for table, cols in schema_notes.items():
        w(f"- **`{table}`**: {cols}")
    w("")
    w("All tables use UUID string primary keys (`VARCHAR(36)`) and `created_at`/`updated_at` timestamps.")
    w("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate drift.db markdown summary")
    parser.add_argument("--stdout", action="store_true", help="print to stdout instead of file")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT, help="output path (default: docs/db_summary.md)")
    args = parser.parse_args()

    if not DB_PATH.exists():
        raise SystemExit(f"Database not found: {DB_PATH}")

    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    md = build_summary(conn)
    conn.close()

    if args.stdout:
        print(md)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(md)
        print(f"Wrote {args.output} ({len(md):,} bytes)")


if __name__ == "__main__":
    main()
